server:
  port: 8082
  #servlet:
    #context-path: /DepartmentService

spring:
  application:
    name: DEPARTMENT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost/department_db
    username: postgres
    password: Rockers12$
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: "Department Service"
    description: "Department CURD REST APIs"
    version: "V1.0"