server:
  port: 8082

spring:
#  application:
#    name: DEPARTMENT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost/department_db
    username: postgres
    password: Rockers12$
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#  config:
#    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: Department Service
    description: Department CURD REST APIs
    environment: ${spring.profiles.active}
    version: v1.0
