server:
  port: 8081

spring:
#  application:
#    name: EMPLOYEE-SERVICE
  datasource:
    url: jdbc:postgresql://localhost/employee_db
    username: postgres
    password: Rockers12$
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  config:
#    import: optional:configserver:http://localhost:8888

test:
  config:
    server: Message From Properties

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

info:
  app:
    name: Employee Service
    description: Employee Service REST CURD APIs
    version: v1.0
